function image_data_final_Complex = MRF_recon()
% This script uses sliding window method and complex coil combination to
% reconstruct .dat raw data and trajectory file. This script requires MiRT
% toolbox, visit their websites for more information:
% https://web.eecs.umich.edu/~fessler/code/
% IUPUT
%       None  User does not need to input any parameter. The script will
%       ask for raw data and trajectory file. The trajectory file is
%       attached as K_Traj4rec.mat in Sample_Data folder.
%
% OUTPUT
% image_data_final_Complex   Reconstructed images.
% 7/2019 Enlin Qian
% # Copyright of the Board of Trustees of Columbia University in the City of New York
%
% some variables: dim1: size of original raw data
% dim2: size of concatenated raw data
% dim3: size of ktrajectory data
% dim4: size of concatenated raw data after cutting rewinders


%% This stage takes in a .dat raw data file and outputs .mat file. 
acquired_raw_data = dat2mat_nonCart();%extract .dat information
%the second dim of acquired data is acquired points, 4th dim is partition number
dim1 = size(acquired_raw_data);
acquired_points = dim1(2);
acquired_raw_data_con = zeros(dim1(1)*dim1(4),dim1(2),dim1(3));%preallocate concatenated raw data
for n1 = 1:dim1(2)
    for n2 = 1:dim1(3)
        acquired_raw_data_con(:,n1,n2) = [acquired_raw_data(:,n1,n2,1);...
            acquired_raw_data(:,n1,n2,2)];%concatenate second partition with first partition
    end
end
dim2 = size(acquired_raw_data_con);

%% Stage 2, load spiral data
[baseFileName,folder] = uigetfile('*.mat','Pick the trajectory file');
fullFileName = fullfile(folder, baseFileName);
load(fullFileName)
acquired_raw_data_con = acquired_raw_data_con(ind(1,:),:,:); % index based on variable "ind"
dim3 = size(traj);
kshots = size(ind,1);
ktraj = repmat(traj,[1,ceil(acquired_points/kshots),1]);
ktraj = ktraj(:,1:acquired_points,:);%repmat spiral data, check first spiral and 49 spiral

%% Stage 3, multiply dcf with raw data
dcf_reshape = dcf(1:dim3(1));
acquired_raw_data_final = bsxfun(@times,acquired_raw_data_con,dcf_reshape');

%% Stage 4, sliding windows reconstruction
Jd = [5,5]; Nd = [256,256]; Kd =Nd.*2;
image_data_final = zeros(Nd(1),Nd(2),dim2(3),acquired_points);
image_data_final_Complex = zeros(Nd(1),Nd(2),acquired_points);
kshot_win = floor(kshots.*0.5);
% setting up parameters for nufft

for n4 = 1:acquired_points%total # of images generated by sliding windows
    SelectedRange = (n4-kshot_win):(n4+kshot_win-1);
    SelectedRange = SelectedRange(SelectedRange > 0 & SelectedRange <= acquired_points);
    ktraj_temp = ktraj(:,SelectedRange,:); %recounstruct using full 48 spirals or partial spirals, trajectory has to be between 0-0.5
    ktraj_temp = reshape(ktraj_temp,[],2); 
    om = squeeze(ktraj_temp.*2.*pi);
    st = nufft_init(om, Nd, Jd, Kd, Nd/2, 'minmax:kb');
    for n5 = 1:dim2(3)
        fprintf('Reconstructing timepoints %d coil %d \n', n4, n5)
        acquired_raw_data_temp = acquired_raw_data_final(:,SelectedRange,n5);
        acquired_raw_data_temp = reshape(acquired_raw_data_temp,[],1);
        image_data_final(:,:,n5,n4) = nufft_adj(acquired_raw_data_temp,st);
    end
end

%% Complex coil combining
for n6 = 1:acquired_points
    fprintf('Complex channel combining for timepoints %d \n', n6)
    sens = Complex_Chan_Combining(image_data_final(:,:,:,n6));
    imtemp2 = squeeze(sum(bsxfun(@times,conj(sens),image_data_final(:,:,:,n6)),3));
    
%     figure(101);
%     imagesc(abs(imtemp2));xlabel(num2str(n4));
%     caxis auto;
%     axis equal tight;
%     colormap gray;
%     drawnow;
    image_data_final_Complex(:, :, n6) = imtemp2;
end
end
