function y = isreal(x)
y = typeof(x);
%y = strcmp(y, 'complex') | strcmp(y, 'dcomplex');
y = strcmp(y, 'uint8') ...
	| strcmp(y, 'int8') ...
	| strcmp(y, 'uint16') ...
	| strcmp(y, 'int16') ...
	| strcmp(y, 'uint32') ...
	| strcmp(y, 'int32') ...
	| strcmp(y, 'float') ...
	| strcmp(y, 'double') ...
	;
